### ISSUE TITLE
Внедрить быстрые ссылки

### ISSUE THREAD

**Issue by Stremuzhevskiy** [kassir-ydirect/project#10]
Мы хотим внедрить быстрые ссылки. Сделали специальной пример http://prntscr.com/7cl46n
1. Набор и текст быстрых ссылок должен быть для каждого объявления одинаковым, таким как в примере
2. Ссылки формируются следующим образом: к урлу страницы добавляется # и ставится порядковый номер. То есть 4 быстрые ссылки, значит 4 адреса, которые выглядят следующим образом:
https://msk.kassir.ru/kassir/event/view/17148#1
https://msk.kassir.ru/kassir/event/view/17148#2
https://msk.kassir.ru/kassir/event/view/17148#3
https://msk.kassir.ru/kassir/event/view/17148#4

**Comment by betadog** [comment]
При создании ссылок в яндекс передаются:
`title` - заголовок ссылки
`href` - сама ссылка по которой переходит юзер

с принципом формирования ссылок понятно: добавляется якорь.
Теперь:
1. как формируются тексты (`title`) для ссылок?
1. куда ведут якоря?

**Comment by Stremuzhevskiy** [comment]
Тексты формируются заранее и одинаковы для всех быстрых ссылок:
1. Купить билеты онлайн
2. Бронирование билетов
3. Афиша в Москве
4. Концерты

Якоря ведут на ту же страницу, на которую ведет объявление.

**Comment by betadog** [comment]
быстрые ссылки будут у всех-всех объявлений?

**Comment by Stremuzhevskiy** [comment]
да

**Comment by betadog** [comment]
вывел в админку текстовое поле для редактирования текста быстрых ссылок.
ссылки для ссылок формируются путем добавления якоря, после якоря ставится транслитерированиое имя текста ссылки
