### ISSUE TITLE
Дубли объявлений в интерфейсе

### ISSUE THREAD

**Issue by Stremuzhevskiy** [kassir-ydirect/project#13]
В кампании hall.2015-04-01» № 12698689  дублируются объявления. При чём в самом скрипте объявление находится в одном экземпляре
Пример 1 Клуб "Театръ"
№ M-890187468
M-922562712

Пример 2 Клуб Yota space (Главклуб)
M-890187328
M-890266455

**Comment by betadog** [comment]
Можно подумать про обратную синхронизацию, тогда каким образом показывать дубли, и самое главное как их объединять.
Предлагаю их просто удалить, для начала.
Возможно они появились при ошибках скрипта.
