### ISSUE TITLE
Список запросов в директе

### ISSUE THREAD

**Issue by Stremuzhevskiy** [kassir-ydirect/project#2]
Список запросов к объявлению в скрипте и интерфейсе директе существенно различаются. В интерфейсе директа их меньше. Необходимо устранить это различие - список запросов из скрипта должен полностью присутствовать в интерфейсе директа.

**Comment by betadog** [comment]
На волгограде сделал объявление для зала. Скрипт честно передает 11 фраз, но яндексе, в своем интерфейсе, показывет только 7 фраз.
```
отправлено в яндекс           | стало в яндексе
------------------------------+-----------------------------------
бар белая лошадь                бар белая лошадь
бар белая лошадь билеты
бар белая лошадь билет
билеты в бар белая лошадь
бар белая лошадь волгоград      бар белая лошадь волгоград
бар белая лошадь купить билеты  бар белая лошадь купить билеты
бар белая лошадь купить билет
репертуар бар белая лошадь      репертуар бар белая лошадь
бар белая лошадь кассы          бар белая лошадь кассы
бар белая лошадь афиша          бар белая лошадь афиша
афиша бар белая лошадь
                                бар белая лошадь билеты -купить
```
Таким образом:
1. фразы `афиша бар белая лошадь` и `бар белая лошадь афиша` для яндекса одно и тоже
2. `купить билеты` и `купить билет` - имеет один смысл
3. `-купить` - тоже понятно откуда взялось

Таким образом имеет смысл изменить алгоритм создания объявления. см другую задачу
