### ISSUE TITLE
Генерация объявлений для событий от 50 билетов

### ISSUE THREAD

**Issue by Stremuzhevskiy** [kassir-ydirect/project#23]
необходимо настроить автоматическую генерацию объявлений для событий, количество билетов для которых от 50 и выше:
- объявления автоматически генерирутся, но не уходят в яндекс;
- нужно сделать механизм модерации объявлений внутри скрипта. После проверки/правки объявлений руками, они отправляются в яндекс на модерацию.

Как мне видится:
- создавать для таких событий отдельную папку - "Модерация", после проработки текстов отмечать галочками нужные события, выбрать "Перенести", выбрать папку куда перенести. Было бы здорово, если возможность нажать "плей" была бы только после переноса в папку, это исключило бы преждевременные запуски :) но и без этого можно запросто обойтись.
Вроде почти все для этого есть, времени много занять не должно.

**Comment by betadog** [comment]
done
