### ISSUE TITLE
Питерские запросы в московском аккаунте

### ISSUE THREAD

**Issue by Stremuzhevskiy** [kassir-ydirect/project#25]
В московском скрипте стали появляться запросы по питеру. 
"санкт-петербург" - не добавляли к событиям.
http://prntscr.com/83ew2r

**Comment by betadog** [comment]
В москве удалил через базу данных объявление: `Китайский цирк 1 января 2016`
Потом в дереве событий сгенерировал одно объявление: в фразах нет СПБ, но есть москва.

Снова удалил объявление и сгенерировал заново с помощью массовых операций. Результат тот же, нет СПБ, есть москва.

Посмотрел некоторые автоматически сгенерированные объявления - у всех СПБ.
буду смотреть/чинить

**Comment by betadog** [comment]
исправил багу
вечером обновим все сайты. утром почищу базу от `новых` объявлений - пусть генерятся заново

**Comment by Stremuzhevskiy** [comment]
Отлично, значит нам лучше приступить к запуску событий завтра?
