### ISSUE TITLE
При редактировании запросов слетает список запросов

### ISSUE THREAD

**Issue by Stremuzhevskiy** [kassir-ydirect/project#26]
Открываем список запросов, удаляем один запрос, сохраняем, затем обновляем  - открываем список вновь, запросов нет.

**Comment by betadog** [comment]
Экспериментировал на локальном - всё ок.
На москве на событии `Китайский цирк 1 января 2016` удалял фразы - всё ок.
Возможно есть какие-то дополнительные условия для проявления данного бага?

**Comment by Stremuzhevskiy** [comment]
Дополнительных условий нет, сегодня работаем, вроде все в порядке пока что. Возможно, это временная проблема была. отпишусь как в случае повтора
