### ISSUE TITLE
Слетают общие настройки кампании

### ISSUE THREAD

**Issue by Stremuzhevskiy** [kassir-ydirect/project#27]
При работе со скриптом - плей/пауза события, слетает карточка организации и настройки кампании: разметка ссылок от яндекса добавляется, стратегия слетает, единые минус слова

**Comment by Stremuzhevskiy** [comment]
Проблема не исчезла и есть на всех аккаунтах, просьба поправить как можно скорее, очень критично

**Comment by betadog** [comment]
#21
