### ISSUE TITLE
Модерация автоматических объявлений

### ISSUE THREAD

**Issue by Stremuzhevskiy** [kassir-ydirect/project#30]
При модерации автоматически сгенерированных объявлений возникает следующее: нажимаем "править", вносим правки, нажимаем "сохранить", индикация меняется  автоматически с "плей" на "стоп". При этом, объявление не уходит в активные. Нужно обновить страницу, найти это объявление и нажать "плей", только тогда оно сгенерируется. 
очень неудобно. Возможно это исправить?

**Comment by betadog** [comment]
`только тогда оно сгенерируется` 
наверное `только тогда оно отправляется в яндекс` ?

**Comment by Stremuzhevskiy** [comment]
да, сорри, только тогда оно отправляется в яндекс

**Comment by betadog** [comment]
Я вижу проблему в смене картинки `play` на `stop` после редактирования объявления, что вводит в заблуждение.
Исправление бага: не менять управляющую иконку. 
Получится следующее: после редактирования объявления достаточно будет тот же нажать на `play` (да, объявление не уберется сразу же со страницы, но после Ф5 его уже не будет)

Годится?

**Comment by Stremuzhevskiy** [comment]
Да, вполне

**Comment by betadog** [comment]
исправлено.
сайты обновятся при следующем обновлении (18-20 авг)
