### ISSUE TITLE
Внедрение новой кампании

### ISSUE THREAD

**Issue by Stremuzhevskiy** [kassir-ydirect/project#6]
О чем договорились:
1. создаем отдельную кампанию, в которую будут отправляться объявления по залам, мероприятиям и событиям.
2. В пунктах "показываемые", "остановленные" и "архивированные" делаем выпадающее меню со списком кампаний.
3. В  выпадающем меню "генерировать объявления" делаем пункт пересоздать (перенести) объявления в новую кампанию. При этом, останавливать их в предыдущей кампании.

**Comment by betadog** [comment]
Интерфейс сделал, 
перенос с ошибкой: объявление не останавливается. починю позжее

**Comment by betadog** [comment]
Ошибка исправлена.
Можно переносить объявления
